export const dictionaryData = [
  {
    ID: 210,
    Code: 210,
    Word: "нам",
    Definition: "Аливаа юмны хөдөлгөөн адил",
    Synonyms: [
      {
        ID: 5416,
        Code: 3526,
        Word: "зовох",
        Definition: "Бие, сэтгэл хэвийн бус, хэцүү байх",
        Level: 1,
      },
      {
        ID: 5417,
        Code: 3527,
        Word: "айх",
        Definition: "Ямар нэгэн аюул, зовлон учрахаас сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5419,
        Code: 3529,
        Word: "бачимдах",
        Definition: "Гэнэтийн зүйлд яарч сандран сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5420,
        Code: 3530,
        Word: "гансрах",
        Definition: "Бодлогошрон сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5421,
        Code: 3531,
        Word: "гашуудах",
        Definition: "Уй гашуу таараад ихэд зовох",
        Level: 2,
      },
      {
        ID: 5422,
        Code: 3532,
        Word: "гуних",
        Definition: "Ямар нэгэн юманд сэтгэл өвдөн зовох",
        Level: 2,
      },
      {
        ID: 5424,
        Code: 3534,
        Word: "гутах",
        Definition: "Сэтгэл санаа доройтон зовох",
        Level: 2,
      },
      {
        ID: 5426,
        Code: 3536,
        Word: "гэнсрэх",
        Definition: "Ямар нэгэн юмыг санаж дурсаад зовох",
        Level: 2,
      },
      {
        ID: 5427,
        Code: 3537,
        Word: "дэнслэх",
        Definition: "Урт хугацаагаар хал үзэж зовох",
        Level: 2,
      },
      {
        ID: 5429,
        Code: 3539,
        Word: "зовних",
        Definition: "Сэтгэл санаа нь зовох",
        Level: 2,
      },
      {
        ID: 5428,
        Code: 3538,
        Word: "зовуурилах",
        Definition: "Өвчин тахлаар бие зовох",
        Level: 2,
      },
      {
        ID: 5430,
        Code: 3540,
        Word: "нүсрэх",
        Definition: "Ядарч туйлдан зовох",
        Level: 2,
      },
      {
        ID: 5431,
        Code: 3541,
        Word: "нэрвэгдэх",
        Definition: "Өвчин тахал, ган гамшигт дайрагдаад зовох",
        Level: 2,
      },
      {
        ID: 5432,
        Code: 3542,
        Word: "нэтрэх",
        Definition: "Урьдахаасаа улам зовох",
        Level: 2,
      },
      {
        ID: 5433,
        Code: 3543,
        Word: "өвдөх",
        Definition: "Бие махбод өвчин тусаж зовох",
        Level: 2,
      },
      {
        ID: 5434,
        Code: 3544,
        Word: "өрсдөх",
        Definition: "Хүнд цохилтод орж зовох",
        Level: 2,
      },
      {
        ID: 5435,
        Code: 3545,
        Word: "тарчлах",
        Definition: "Хал үзэж ихэд зовох",
        Level: 2,
      },
      {
        ID: 5436,
        Code: 3546,
        Word: "үлтрэх",
        Definition: "Мөлжил дарлалыг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5437,
        Code: 3547,
        Word: "хивших",
        Definition: "Азгүй зүйл тохиолдож энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5438,
        Code: 3548,
        Word: "хүчирдэх",
        Definition: "Хүчир бэрхийг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5439,
        Code: 3549,
        Word: "шаналах",
        Definition: "Сэтгэл санаа энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5440,
        Code: 3550,
        Word: "шартах",
        Definition: "Архинд согтоод бие зовох",
        Level: 2,
      },
      {
        ID: 5441,
        Code: 3551,
        Word: "ширхийх",
        Definition: "Санаа зовох",
        Level: 2,
      },
      {
        ID: 5442,
        Code: 3552,
        Word: "эвхрэх",
        Definition: "Сэтгэл санаа ихэд гутран зовох",
        Level: 2,
      },
      {
        ID: 5443,
        Code: 3553,
        Word: "эвэрлэх",
        Definition: "Сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5444,
        Code: 3554,
        Word: "эвэршээх",
        Definition: "Тэсэхийн аргагүй өвдөж зовох",
        Level: 2,
      },
      {
        ID: 5445,
        Code: 3555,
        Word: "эмгэнэх",
        Definition: "Сэтгэл санаа туйлаар шаналан зовох",
        Level: 2,
      },
      {
        ID: 5446,
        Code: 3556,
        Word: "эмтрэх",
        Definition: "Эмгэнэн зовох",
        Level: 2,
      },
      {
        ID: 5447,
        Code: 3557,
        Word: "энслэх",
        Definition: "Хүн ихэд гэмшин зовох",
        Level: 2,
      },
      {
        ID: 5448,
        Code: 3558,
        Word: "энэлэх",
        Definition: "Хүний ихэд гасалж зовох",
        Level: 2,
      },
      {
        ID: 5423,
        Code: 3533,
        Word: "гуньхрах",
        Definition: "Ихэд гуних",
        Level: 3,
      },
      {
        ID: 5425,
        Code: 3535,
        Word: "гутрах",
        Definition: "Гутах",
        Level: 3,
      },
    ],
  },
  {
    ID: 1204,
    Code: 1141,
    Word: "нам",
    Definition: "Би гэдгийн хувилсан хэлбэр",
    Synonyms: [
      {
        ID: 5416,
        Code: 3526,
        Word: "зовох",
        Definition: "Бие, сэтгэл хэвийн бус, хэцүү байх",
        Level: 1,
      },
      {
        ID: 5417,
        Code: 3527,
        Word: "айх",
        Definition: "Ямар нэгэн аюул, зовлон учрахаас сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5419,
        Code: 3529,
        Word: "бачимдах",
        Definition: "Гэнэтийн зүйлд яарч сандран сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5420,
        Code: 3530,
        Word: "гансрах",
        Definition: "Бодлогошрон сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5421,
        Code: 3531,
        Word: "гашуудах",
        Definition: "Уй гашуу таараад ихэд зовох",
        Level: 2,
      },
      {
        ID: 5422,
        Code: 3532,
        Word: "гуних",
        Definition: "Ямар нэгэн юманд сэтгэл өвдөн зовох",
        Level: 2,
      },
      {
        ID: 5424,
        Code: 3534,
        Word: "гутах",
        Definition: "Сэтгэл санаа доройтон зовох",
        Level: 2,
      },
      {
        ID: 5426,
        Code: 3536,
        Word: "гэнсрэх",
        Definition: "Ямар нэгэн юмыг санаж дурсаад зовох",
        Level: 2,
      },
      {
        ID: 5427,
        Code: 3537,
        Word: "дэнслэх",
        Definition: "Урт хугацаагаар хал үзэж зовох",
        Level: 2,
      },
      {
        ID: 5429,
        Code: 3539,
        Word: "зовних",
        Definition: "Сэтгэл санаа нь зовох",
        Level: 2,
      },
      {
        ID: 5428,
        Code: 3538,
        Word: "зовуурилах",
        Definition: "Өвчин тахлаар бие зовох",
        Level: 2,
      },
      {
        ID: 5430,
        Code: 3540,
        Word: "нүсрэх",
        Definition: "Ядарч туйлдан зовох",
        Level: 2,
      },
      {
        ID: 5431,
        Code: 3541,
        Word: "нэрвэгдэх",
        Definition: "Өвчин тахал, ган гамшигт дайрагдаад зовох",
        Level: 2,
      },
      {
        ID: 5432,
        Code: 3542,
        Word: "нэтрэх",
        Definition: "Урьдахаасаа улам зовох",
        Level: 2,
      },
      {
        ID: 5433,
        Code: 3543,
        Word: "өвдөх",
        Definition: "Бие махбод өвчин тусаж зовох",
        Level: 2,
      },
      {
        ID: 5434,
        Code: 3544,
        Word: "өрсдөх",
        Definition: "Хүнд цохилтод орж зовох",
        Level: 2,
      },
      {
        ID: 5435,
        Code: 3545,
        Word: "тарчлах",
        Definition: "Хал үзэж ихэд зовох",
        Level: 2,
      },
      {
        ID: 5436,
        Code: 3546,
        Word: "үлтрэх",
        Definition: "Мөлжил дарлалыг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5437,
        Code: 3547,
        Word: "хивших",
        Definition: "Азгүй зүйл тохиолдож энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5438,
        Code: 3548,
        Word: "хүчирдэх",
        Definition: "Хүчир бэрхийг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5439,
        Code: 3549,
        Word: "шаналах",
        Definition: "Сэтгэл санаа энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5440,
        Code: 3550,
        Word: "шартах",
        Definition: "Архинд согтоод бие зовох",
        Level: 2,
      },
      {
        ID: 5441,
        Code: 3551,
        Word: "ширхийх",
        Definition: "Санаа зовох",
        Level: 2,
      },
      {
        ID: 5442,
        Code: 3552,
        Word: "эвхрэх",
        Definition: "Сэтгэл санаа ихэд гутран зовох",
        Level: 2,
      },
      {
        ID: 5443,
        Code: 3553,
        Word: "эвэрлэх",
        Definition: "Сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5444,
        Code: 3554,
        Word: "эвэршээх",
        Definition: "Тэсэхийн аргагүй өвдөж зовох",
        Level: 2,
      },
      {
        ID: 5445,
        Code: 3555,
        Word: "эмгэнэх",
        Definition: "Сэтгэл санаа туйлаар шаналан зовох",
        Level: 2,
      },
      {
        ID: 5446,
        Code: 3556,
        Word: "эмтрэх",
        Definition: "Эмгэнэн зовох",
        Level: 2,
      },
      {
        ID: 5447,
        Code: 3557,
        Word: "энслэх",
        Definition: "Хүн ихэд гэмшин зовох",
        Level: 2,
      },
      {
        ID: 5448,
        Code: 3558,
        Word: "энэлэх",
        Definition: "Хүний ихэд гасалж зовох",
        Level: 2,
      },
      {
        ID: 5423,
        Code: 3533,
        Word: "гуньхрах",
        Definition: "Ихэд гуних",
        Level: 3,
      },
      {
        ID: 5425,
        Code: 3535,
        Word: "гутрах",
        Definition: "Гутах",
        Level: 3,
      },
    ],
  },
  {
    ID: 1726,
    Code: 1663,
    Word: "нам",
    Definition:
      "Улс орны доторх нэгэн хэсгийн эрх ашгийг хамгаалж үзэл бодол, сонирхлоороо нэгдсэн хэсэг хүмүүсийн бүлэг",
    Synonyms: [
      {
        ID: 5416,
        Code: 3526,
        Word: "зовох",
        Definition: "Бие, сэтгэл хэвийн бус, хэцүү байх",
        Level: 1,
      },
      {
        ID: 5417,
        Code: 3527,
        Word: "айх",
        Definition: "Ямар нэгэн аюул, зовлон учрахаас сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5419,
        Code: 3529,
        Word: "бачимдах",
        Definition: "Гэнэтийн зүйлд яарч сандран сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5420,
        Code: 3530,
        Word: "гансрах",
        Definition: "Бодлогошрон сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5421,
        Code: 3531,
        Word: "гашуудах",
        Definition: "Уй гашуу таараад ихэд зовох",
        Level: 2,
      },
      {
        ID: 5422,
        Code: 3532,
        Word: "гуних",
        Definition: "Ямар нэгэн юманд сэтгэл өвдөн зовох",
        Level: 2,
      },
      {
        ID: 5424,
        Code: 3534,
        Word: "гутах",
        Definition: "Сэтгэл санаа доройтон зовох",
        Level: 2,
      },
      {
        ID: 5426,
        Code: 3536,
        Word: "гэнсрэх",
        Definition: "Ямар нэгэн юмыг санаж дурсаад зовох",
        Level: 2,
      },
      {
        ID: 5427,
        Code: 3537,
        Word: "дэнслэх",
        Definition: "Урт хугацаагаар хал үзэж зовох",
        Level: 2,
      },
      {
        ID: 5429,
        Code: 3539,
        Word: "зовних",
        Definition: "Сэтгэл санаа нь зовох",
        Level: 2,
      },
      {
        ID: 5428,
        Code: 3538,
        Word: "зовуурилах",
        Definition: "Өвчин тахлаар бие зовох",
        Level: 2,
      },
      {
        ID: 5430,
        Code: 3540,
        Word: "нүсрэх",
        Definition: "Ядарч туйлдан зовох",
        Level: 2,
      },
      {
        ID: 5431,
        Code: 3541,
        Word: "нэрвэгдэх",
        Definition: "Өвчин тахал, ган гамшигт дайрагдаад зовох",
        Level: 2,
      },
      {
        ID: 5432,
        Code: 3542,
        Word: "нэтрэх",
        Definition: "Урьдахаасаа улам зовох",
        Level: 2,
      },
      {
        ID: 5433,
        Code: 3543,
        Word: "өвдөх",
        Definition: "Бие махбод өвчин тусаж зовох",
        Level: 2,
      },
      {
        ID: 5434,
        Code: 3544,
        Word: "өрсдөх",
        Definition: "Хүнд цохилтод орж зовох",
        Level: 2,
      },
      {
        ID: 5435,
        Code: 3545,
        Word: "тарчлах",
        Definition: "Хал үзэж ихэд зовох",
        Level: 2,
      },
      {
        ID: 5436,
        Code: 3546,
        Word: "үлтрэх",
        Definition: "Мөлжил дарлалыг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5437,
        Code: 3547,
        Word: "хивших",
        Definition: "Азгүй зүйл тохиолдож энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5438,
        Code: 3548,
        Word: "хүчирдэх",
        Definition: "Хүчир бэрхийг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5439,
        Code: 3549,
        Word: "шаналах",
        Definition: "Сэтгэл санаа энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5440,
        Code: 3550,
        Word: "шартах",
        Definition: "Архинд согтоод бие зовох",
        Level: 2,
      },
      {
        ID: 5441,
        Code: 3551,
        Word: "ширхийх",
        Definition: "Санаа зовох",
        Level: 2,
      },
      {
        ID: 5442,
        Code: 3552,
        Word: "эвхрэх",
        Definition: "Сэтгэл санаа ихэд гутран зовох",
        Level: 2,
      },
      {
        ID: 5443,
        Code: 3553,
        Word: "эвэрлэх",
        Definition: "Сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5444,
        Code: 3554,
        Word: "эвэршээх",
        Definition: "Тэсэхийн аргагүй өвдөж зовох",
        Level: 2,
      },
      {
        ID: 5445,
        Code: 3555,
        Word: "эмгэнэх",
        Definition: "Сэтгэл санаа туйлаар шаналан зовох",
        Level: 2,
      },
      {
        ID: 5446,
        Code: 3556,
        Word: "эмтрэх",
        Definition: "Эмгэнэн зовох",
        Level: 2,
      },
      {
        ID: 5447,
        Code: 3557,
        Word: "энслэх",
        Definition: "Хүн ихэд гэмшин зовох",
        Level: 2,
      },
      {
        ID: 5448,
        Code: 3558,
        Word: "энэлэх",
        Definition: "Хүний ихэд гасалж зовох",
        Level: 2,
      },
      {
        ID: 5423,
        Code: 3533,
        Word: "гуньхрах",
        Definition: "Ихэд гуних",
        Level: 3,
      },
      {
        ID: 5425,
        Code: 3535,
        Word: "гутрах",
        Definition: "Гутах",
        Level: 3,
      },
    ],
  },
  {
    ID: 5737,
    Code: 3847,
    Word: "нам",
    Definition: "Юманд багтах зүйл",
    Synonyms: [
      {
        ID: 5416,
        Code: 3526,
        Word: "зовох",
        Definition: "Бие, сэтгэл хэвийн бус, хэцүү байх",
        Level: 1,
      },
      {
        ID: 5417,
        Code: 3527,
        Word: "айх",
        Definition: "Ямар нэгэн аюул, зовлон учрахаас сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5419,
        Code: 3529,
        Word: "бачимдах",
        Definition: "Гэнэтийн зүйлд яарч сандран сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5420,
        Code: 3530,
        Word: "гансрах",
        Definition: "Бодлогошрон сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5421,
        Code: 3531,
        Word: "гашуудах",
        Definition: "Уй гашуу таараад ихэд зовох",
        Level: 2,
      },
      {
        ID: 5422,
        Code: 3532,
        Word: "гуних",
        Definition: "Ямар нэгэн юманд сэтгэл өвдөн зовох",
        Level: 2,
      },
      {
        ID: 5424,
        Code: 3534,
        Word: "гутах",
        Definition: "Сэтгэл санаа доройтон зовох",
        Level: 2,
      },
      {
        ID: 5426,
        Code: 3536,
        Word: "гэнсрэх",
        Definition: "Ямар нэгэн юмыг санаж дурсаад зовох",
        Level: 2,
      },
      {
        ID: 5427,
        Code: 3537,
        Word: "дэнслэх",
        Definition: "Урт хугацаагаар хал үзэж зовох",
        Level: 2,
      },
      {
        ID: 5429,
        Code: 3539,
        Word: "зовних",
        Definition: "Сэтгэл санаа нь зовох",
        Level: 2,
      },
      {
        ID: 5428,
        Code: 3538,
        Word: "зовуурилах",
        Definition: "Өвчин тахлаар бие зовох",
        Level: 2,
      },
      {
        ID: 5430,
        Code: 3540,
        Word: "нүсрэх",
        Definition: "Ядарч туйлдан зовох",
        Level: 2,
      },
      {
        ID: 5431,
        Code: 3541,
        Word: "нэрвэгдэх",
        Definition: "Өвчин тахал, ган гамшигт дайрагдаад зовох",
        Level: 2,
      },
      {
        ID: 5432,
        Code: 3542,
        Word: "нэтрэх",
        Definition: "Урьдахаасаа улам зовох",
        Level: 2,
      },
      {
        ID: 5433,
        Code: 3543,
        Word: "өвдөх",
        Definition: "Бие махбод өвчин тусаж зовох",
        Level: 2,
      },
      {
        ID: 5434,
        Code: 3544,
        Word: "өрсдөх",
        Definition: "Хүнд цохилтод орж зовох",
        Level: 2,
      },
      {
        ID: 5435,
        Code: 3545,
        Word: "тарчлах",
        Definition: "Хал үзэж ихэд зовох",
        Level: 2,
      },
      {
        ID: 5436,
        Code: 3546,
        Word: "үлтрэх",
        Definition: "Мөлжил дарлалыг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5437,
        Code: 3547,
        Word: "хивших",
        Definition: "Азгүй зүйл тохиолдож энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5438,
        Code: 3548,
        Word: "хүчирдэх",
        Definition: "Хүчир бэрхийг амсаж зовох",
        Level: 2,
      },
      {
        ID: 5439,
        Code: 3549,
        Word: "шаналах",
        Definition: "Сэтгэл санаа энэлэн зовох",
        Level: 2,
      },
      {
        ID: 5440,
        Code: 3550,
        Word: "шартах",
        Definition: "Архинд согтоод бие зовох",
        Level: 2,
      },
      {
        ID: 5441,
        Code: 3551,
        Word: "ширхийх",
        Definition: "Санаа зовох",
        Level: 2,
      },
      {
        ID: 5442,
        Code: 3552,
        Word: "эвхрэх",
        Definition: "Сэтгэл санаа ихэд гутран зовох",
        Level: 2,
      },
      {
        ID: 5443,
        Code: 3553,
        Word: "эвэрлэх",
        Definition: "Сэтгэл зовох",
        Level: 2,
      },
      {
        ID: 5444,
        Code: 3554,
        Word: "эвэршээх",
        Definition: "Тэсэхийн аргагүй өвдөж зовох",
        Level: 2,
      },
      {
        ID: 5445,
        Code: 3555,
        Word: "эмгэнэх",
        Definition: "Сэтгэл санаа туйлаар шаналан зовох",
        Level: 2,
      },
      {
        ID: 5446,
        Code: 3556,
        Word: "эмтрэх",
        Definition: "Эмгэнэн зовох",
        Level: 2,
      },
      {
        ID: 5447,
        Code: 3557,
        Word: "энслэх",
        Definition: "Хүн ихэд гэмшин зовох",
        Level: 2,
      },
      {
        ID: 5448,
        Code: 3558,
        Word: "энэлэх",
        Definition: "Хүний ихэд гасалж зовох",
        Level: 2,
      },
      {
        ID: 5423,
        Code: 3533,
        Word: "гуньхрах",
        Definition: "Ихэд гуних",
        Level: 3,
      },
      {
        ID: 5425,
        Code: 3535,
        Word: "гутрах",
        Definition: "Гутах",
        Level: 3,
      },
    ],
  },
];
